export const IMAGES = {
  maymac: "/icons/fmrp/maymac2.png",
  dienmay: "/icons/fmrp/dienmay1.png",
  cokhi: "/icons/fmrp/cokhi1.png",
  thucpham: "/icons/fmrp/thucpham1.png",
  nongnghiep: "/icons/fmrp/nongnghiep1.png",
  go: "/icons/fmrp/go1.png",
  nhua: "/icons/fmrp/nhua1.png",
  giay: "/icons/fmrp/giay1.png",
  khac: "/icons/fmrp/khac1.png",
  nguyenVatLieu: "/icons/fmrp/nguyenVatLieu.png",
  baoCao: "/icons/fmrp/baoCao.png",
  banHang: "/icons/fmrp/banHang.png",
  nhaCungCap: "/icons/fmrp/nhaCungCap.png",
  sanXuat: "/icons/fmrp/sanXuat.png",
  khoHang: "/icons/fmrp/khoHang.png",
  muaHang: "/icons/fmrp/muaHang.png",
  nhanSu: "/icons/fmrp/nhanSu.png",
  khachHang: "/icons/fmrp/khachHang.png",
  star: "/icons/fmrp/star.png",
  glass: "/icons/fmrp/glass.png",
  fimo: "/icons/fmrp/fimo1.webp",
  lenhSanXuat: "/icons/fmrp/lenhSanXuat1.png",
  lotDate: "/icons/fmrp/lotDate2.png",
  fmrpApp: "/icons/fmrp/fmrpApp.png",
  banner: "/banner.png",
};
